### ISSUE TITLE
MultiDex 开启失败

### ISSUE THREAD

**Issue by changjiashuai** [Werb/MoreType#5]
`
08-31 15:12:07.213 21909-21909/com.arashivision.pro E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.arashivision.pro, PID: 21909
                                                                      java.lang.NoSuchMethodError: No direct method <init>(ILkotlin/reflect/KClass;)V in class Lcom/werb/library/MoreViewType; or its super classes (declaration of 'com.werb.library.MoreViewType' appears in /data/app/com.arashivision.pro-1/base.apk)
                                                                          at com.arashivision.pro.component.AppSettingsActivity$InfoViewType.<init>(AppSettingsActivity.kt:45)
                                                                          at com.arashivision.pro.component.AppSettingsActivity.initRecyclerView(AppSettingsActivity.kt:38)
                                                                          at com.arashivision.pro.component.AppSettingsActivity.onCreate(AppSettingsActivity.kt:26)
                                                                          at android.app.Activity.performCreate(Activity.java:6876)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                          at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:158)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08-31 15:12:26.363 21909-21909/com.arashivision.pro I/Process: Sending signal. PID: 21909 SIG: 9
`

**Comment by werbhelius** [comment]
@changjiashuai 
```gradle
compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
```
这个有依赖么？

**Comment by changjiashuai** [comment]
@Werb 有的 beta2 写法没问题（但是RecyclerView会有重用错乱问题）beta10就出现这个错误crash了

**Comment by werbhelius** [comment]
@changjiashuai beta10 改了一些写法，你可以下载最新的 master 代码看一下，并且我在代码中开启了 MultiDex 但没有出现你说的问题，你对照我的代码看一下。目前这个样子，我不能准确的判断是哪里出了问题，希望你可以提供多一些的信息。
